<?php
/*
________________________________________________________________________________________
*   Create a PHP array to enable access to gallery of Road to 2012 photos
*   
*   (c) 2013 Thomas Daly
________________________________________________________________________________________
*/

	$_SERVER['SERVER_NAME'] = 'bramber';
	require 'site/config.php';

	$filegrp = new FileGroup();
	$filegrp->scan(MASTER_IMAGE_PATH, '/.*\.jpg$/');

	$hours = array();
	$minutes = array();
	$seconds = array();
	

	$i = 0;
	foreach ($filegrp->listFiles() as $file)
	{

		$results = array();
	
		// read timecode (2-digit number shown in photo) from filename
		preg_match('/\d\d\D\D(\d\d)$/', $file->filename, $results);
	
		$timecode = (int)$results[1];

		//echo $file->filename . "\t" . $timecode . "\n";

		// if filename contains the letter 'h', will need to go in hours array
		if (preg_match('/.+h.+/', $file->filename, $results))
		{
			$hours[$timecode][] = $file->filename;
		}

		// if filename contains the letter 'm', will need to go in minutes array
		if (preg_match('/.+m.+/', $file->filename, $results))
        {
                $minutes[$timecode][] = $file->filename;
        }

		// if filename contains the letter 's', will need to go in seconds array
        if (preg_match('/.+s.+/', $file->filename, $results))
        {
                $seconds[$timecode][] = $file->filename;
        }

		$i++;

	}
/*
	echo "Hours:\n";
	print_r($hours);

	echo "Minutes:\n";
	print_r($minutes);

	echo "Seconds:\n";
	print_r($seconds);

	echo "Total processed: $i\n";
*/	


	// capture the HTML output of a form display script as a string, so it can be sent as an email instead of to the browser
	ob_start();

	echo "<?php\n// Code auto-generated by buildarray.php on " . date('d M Y') . "\n\n";

	// create PHP array
	echo "\$h = array();\n";
	
	reset($hours);
	$n = 0;
	while (list($key, $this_array) = each($hours))
	{
		echo "\$h[$key] = array(";
		for ($i=0; $i<count($this_array); $i++)
		{
			$value = $this_array[$i];
			echo "'$value'";
			if ($i < (count($this_array) - 1))
				echo ', ';
		}
		echo ");\n";	    
	    $n++;
	}

	echo "\n\n\$m = array();\n";
	reset($minutes);
	$n = 0;
	while (list($key, $this_array) = each($minutes))
	{
		echo "\$m[$key] = array(";
		for ($i=0; $i<count($this_array); $i++)
		{
			$value = $this_array[$i];
			echo "'$value'";
			if ($i < (count($this_array) - 1))
				echo ', ';
		}
		echo ");\n";	    
	    $n++;
	}

	echo "\n\n\$s = array();\n";
	reset($seconds);
	$n = 0;
	while (list($key, $this_array) = each($seconds))
	{
		echo "\$s[$key] = array(";
		for ($i=0; $i<count($this_array); $i++)
		{
			$value = $this_array[$i];
			echo "'$value'";
			if ($i < (count($this_array) - 1))
				echo ', ';
		}
		echo ");\n";	    
	    $n++;
	}

	echo "?>";
// the code captured in the buffer is now copied to variable $form_html
	file_put_contents('test.php', ob_get_contents());

// Clean (erase) the output buffer and turn off output buffering 	
	ob_end_clean();

?>

